### ISSUE TITLE
Problem with redirect after successful login

### ISSUE THREAD

**Issue by cpinkl** [ldaptools/ldaptools-bundle#12]
Hello,

I've tried to implement the Login using AD. All works well expect the redirect after the login.

Maybe it would be nice to use the setting from default symfony ("default_target_path", "always_use_default_target_path") to configure the redirect.

Thanks in advance,
Best regards,

**Comment by ChadSikorra** [comment]
Hmm...yeah, I shouldn't have hard coded that it seems. Looking at it again I'm relying on `_security.main.target_path` for a redirect on success, but if that does not exist it just uses `/`. This should be configurable.

**Comment by ChadSikorra** [comment]
I'll have to re-implement the `default_target_path` type parameters underneath `ldap_tools.security`, as the other target path parameters aren't actually exposed in a way that I can figure out what they are in the Guard component. Anywho, I should be able to get around to doing this soon.

**Comment by cpinkl** [comment]
I've looked into it a bit and found a possibility to reuse the DefaultAuthenticationSuccessHandler direct. I've created a Service 

`<service id="ldap_tools.security.authentication_handler" 
                 class="Symfony\Component\Security\Http\Authentication\DefaultAuthenticationSuccessHandler"
                 parent="security.authentication.success_handler"
                 public="false" />`

Added the Argument `<argument type="service" id="ldap_tools.security.authentication_handler" />` to the "ldap_tools.security.ldap_guard_authenticator" service and used it in the Guard

`public function onAuthenticationSuccess(Request $request, TokenInterface $token, $providerKey)
    {
        return $this->successHander->onAuthenticationSuccess($request, $token);
    }`

**Comment by ChadSikorra** [comment]
Thanks for checking into it! I was wondering if that would pass the arguments from the firewall section with it or not.

**Comment by ChadSikorra** [comment]
So I can set it up to work that way with the default success/failure handlers, but I don't think the options from the firewall are being respected in them. When I dump the instantiated service in the Guard it just has the default options and not what was set on that firewall instance. Is it actually working for you?

**Comment by ChadSikorra** [comment]
In the Symfony GuardAuthenticationFactory it doesn't have those options at all in it. Where as in the form one it does. So I don't think it would be possible to get this info in the guard. Unless I'm missing something here? I'm tempted to just make it an event where you can set the redirect response yourself based on the token/request info. That would provide the greatest flexibility anyway.

**Comment by cpinkl** [comment]
I've now tested my solution and you are right. You just get a `DefaultAuthenticationSuccessHandler `with default options.

Maybe it would be a good solution to make it configureable using `ldap_tools.security` and as a second option overwrite it using an event.

**Comment by ChadSikorra** [comment]
The way I'm currently going about it now is to have `ldap_tools.security.guard.auth_success` and `ldap_tools.security.guard.auth_failure` where you can set the default target path, whether to always use it, failure path, etc. Then I'll have an event that will contain the `RedirectResponse` based on that default info and you can change it there if needed in the event.

The other problem is that there is no way to really specify per-firewall config options in the Guard. So if you have multiple firewalls defined and the LDAP Guard in each, then it will always get these same redirection settings (which might not be preferred). This is where the event would be most useful I guess. I opened an issue on Symfony for it, but I'm not sure where it makes sense to solve that issue.

https://github.com/symfony/symfony/issues/22071

**Comment by ChadSikorra** [comment]
Fixed with: https://github.com/ldaptools/ldaptools-bundle/commit/f03e1f6ed57be2f37cce661bc97196d145ee0291

You can set a default target path like so:

```yaml
ldap_tools:
    security:
        guard:
            default_target_path: '/foo'
```

All of the new settings are mentioned here: 

https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/Configuration-Reference.md#guard

The new event names were you can set the response yourself are mentioned here: 

https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/Bundle-Event-Reference.md

Let me know if you notice any issues with it. I'll be adding a few other configuration items soon as well, such as: use_forward, username_parameter, password_parameter, etc.

**Comment by murman-lexus** [comment]
Hello.
I saw **use_forward** parameter in: https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/Configuration-Reference.md#guard

Did you added **use_forward**  to your bundle?

Because I tried to use it and have no effect, after login always redirect to **default_target_path** 

Can be problem With Using FOS USER BUNLDE?


My Security.yml:
```
        main:
            pattern:            /.*
            context:            user
            form_login:
                provider:       fos_userbundle
                login_path:     fos_user_security_login
                use_forward:    true
                check_path:     fos_user_security_check
                failure_path:   null
            guard:
                authenticators:
                    - ldap_tools.security.ldap_guard_authenticator
            logout:
                path:           fos_user_security_logout
                target:         fos_user_security_login
```

and Ldap_tools config:
```
ldap_tools:
    domains:
        my_ldap:
            domain_name: '%ldap.domain_name%'
            servers: '%ldap.servers%'
    security:
        guard:
            login_path: fos_user_security_login
            default_target_path: test_page
            use_forward: true
```

when I disabled ldap_tools.security.ldap_guard_authenticator in config
```
#            guard:
#                authenticators:
#                    - ldap_tools.security.ldap_guard_authenticator
```
forwarding worked correct  (but with with standatr FOS auth=))

Thanks in advance.
