### ISSUE TITLE
Help wanted for creating users in DB after successfull LDAP login

### ISSUE THREAD

**Issue by pascalbeynel** [ldaptools/ldaptools-bundle#18]
Hello,

This is an help wanted issue :)

This bundle seems very complete but I think i'm trying to make something that can't be done.
I have a custom provider (I also tried with FOSuserBundle). I want to authenticate user from an openldap LDAP. If the authentication is successfull AND user doesn't exist in my ORM User entity, then i can create it using the Ldap informations provided. 
Then, session start with my ORM User entity.

It seems through you documentation, that ORM User entity must exists in database to be able to login. In this way, the admin must create account in both ldap and application and we don't want to double each account creation.

Have you any advices for my problem ? Thanks.
Best regards

**Comment by ChadSikorra** [comment]
I have done this in a project I'm working on. Basically what you need to do is chain the database and LDAP user providers (database should be before LDAP), then also use the `ldap_tools_bundle.login.success` event. In the event check to see if the user is new by using the `getId()` method (only empty if not in the database). If it is new then save it to the database.

To do this you also need to use a custom user class for this bundle and point it to your user entity for the database. ie:

```yaml
ldap_tools:
    security:
        user: AppBundle\Entity\AppUser
```

The custom user needs to implement `LdapTools\Bundle\LdapToolsBundle\Security\User\LdapUserInterface`. I can write up a cookbook article later on the exact steps to do something like this. But those are the basic steps.

**Comment by pascalbeynel** [comment]
Thank you very much. I'm gonna try this. All coobook article are welcomed :D

**Comment by ChadSikorra** [comment]
This process is now documented here:

https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/Save-LDAP-Users-to-the-Database-After-Login.md

Also added a link on the readme. Let me know if you run into any issues with it or have any questions!

**Comment by Xeyos88** [comment]
Hello,
I'm trying to do what's described in the link.
The problem is that I use FOS and it seems not to work.
Any suggestions?

**Comment by ChadSikorra** [comment]
@Xeyos88 What's the error message or problem you're running into?

**Comment by Xeyos88** [comment]
If the user doesn't pre-exist in DB, i have invalid credential message and doesn't create the user in db

**Comment by Xeyos88** [comment]
After some changes i have this error if the user doen't exist in DB:

"Authentication request could not be processed due to a system problem"
