### ISSUE TITLE
Non existent parameter "username" when using bind_format

### ISSUE THREAD

**Issue by Marizza69** [ldaptools/ldaptools-bundle#23]
I am trying to configure a guard. Since I need to bind with the DN and I don't want to let the user type it the full DN as username, I am trying to use the parameter "bind_format" from ldaptools.
bind_format: "CN=%username%,DC=example,DC=org"

When I try to run my application Symfony reports
PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException: You have requested a non-existent parameter "username". Did you mean this: "swiftmailer.mailer.default.transport.smtp.username"? in /home/mz/Programming/personal/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ParameterBag/ParameterBag.php:100

**Comment by ChadSikorra** [comment]
Does `bind_format: "CN=%%username%%,DC=example,DC=org" work? That should escape the `%`, which Symfony treats special for parameters. I probably should have picked a different character than `%` for this in LdapTools. But I wasn't thinking of Symfony at the time :/

**Comment by Marizza69** [comment]
Bingo - that was the reason!
Maybe you can update the docs and mention the need of double '%'?
Thanks!

**Comment by ChadSikorra** [comment]
Good point on the docs update. It is now explicitly noted here:

https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/LDAP-Authentication-Provider.md#ldap-authentication-username

I will be adding an additional config option soon to allow an additional LDAP query to fully resolve the DN prior to binding, so in the future the `bind_format` can be avoided altogether.
