### ISSUE TITLE
Search by `cn` instead of `username` 

### ISSUE THREAD

**Issue by eSlider** [ldaptools/ldaptools-bundle#24]
Is it possible to configure how to get user not just [by `username`](https://github.com/ldaptools/ldaptools-bundle/blob/b7e5b978bebf864db40073909940b6a99308a176/Security/User/LdapUserProvider.php#L92), but by some other key name, like `cn`?

**Comment by ChadSikorra** [comment]
Yes, that's possible. Is this for OpenLDAP? You can follow the steps here:

https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/LDAP-Authentication-Provider.md#mapping-ldap-attributes

Just replace any occurrence of `ad` with `openldap` in the steps. And set the username mapping to cn.  The default LdapTools library OpenLDAP schema maps username to UID (on the master branch anyway, but not in the most recent tagged version).

**Comment by eSlider** [comment]
@ChadSikorra, thank you!
