### ISSUE TITLE
Maping attributes to user entitiy

### ISSUE THREAD

**Issue by mcgoode** [ldaptools/ldaptools-bundle#31]
So maybe i'm missing it since i'm new to symfony in general, but how can I get more attributes, not just guid and username to be persisted in the database?

Do I inject the LdapManager into the loginEventListener or is there a way to call those attributes via config?

Thanks

**Comment by ChadSikorra** [comment]
I have a way to select additional attributes for the user that gets loaded when you're using the default user from this bundles user provider:

https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/Configuration-Reference.md#additional_attributes

But if you're using a custom user class with this bundle, then you'll have to resort to using the LdapManager service to query LDAP for the user again in the LDAP login success event:

https://github.com/ldaptools/ldaptools-bundle/blob/master/Resources/doc/Save-LDAP-Users-to-the-Database-After-Login.md#create-an-event-to-save-your-user-to-the-db-on-login

Let me know if you need more details. It would be nice to have a better way of doing this though. Perhaps via annotation or some other way.

**Comment by mcgoode** [comment]
Yeah I am using a custom user class so I can store information in the database, I wanted to make sure I wasn't missing an easier. I will just re-query AD on the login success event. Thanks for the prompt response.

Man annotations would be pretty slick when using a custom user class. 
something like:
```
/*
* LdapTools("map=givenName")
*/
private $lastName;
```

**Comment by ChadSikorra** [comment]
I agree...that would be really slick. I already have some annotations related to forms, so maybe it wouldn't be too hard to add them for the purpose of syncing attributes to entities on certain Doctrine lifecycle events, like creation and modification.
