### ISSUE TITLE
how to install with php 7.1.4

### ISSUE THREAD

**Issue by EJNB** [ldaptools/ldaptools-bundle#37]
When I try to install ldap-tools bundle I get the following error:

Problem 1
    - ldaptools/ldaptools v0.25.2 requires php >=5.6 -> your PHP version (7.1.4) overridden by "config.platform.php" version (5.3.9) does not satisfy that requirement.
    - ldaptools/ldaptools v0.25.1 requires php >=5.6 -> your PHP version (7.1.4) overridden by "config.platform.php" version (5.3.9) does not satisfy that requirement.
    - ldaptools/ldaptools v0.25.0 requires php >=5.6 -> your PHP version (7.1.4) overridden by "config.platform.php" version (5.3.9) does not satisfy that requirement.
    - ldaptools/ldaptools-bundle 0.8.1 requires ldaptools/ldaptools >=0.25 -> satisfiable by ldaptools/ldaptools[v0.25.0, v0.25.1, v0.25.2].
    - Installation request for ldaptools/ldaptools-bundle ^0.8.1 -> satisfiable by ldaptools/ldaptools-bundle[0.8.1].

**Comment by ChadSikorra** [comment]
This is an issue with the composer.json in your Symfony project. You need to remove this line:

https://github.com/symfony/symfony-standard/blob/3.3/composer.json#L51

**Comment by ChadSikorra** [comment]
Closing this out since it's an issue with the Symfony composer file. If you still need any help with the change I mentioned let me know.
