### ISSUE TITLE
Profiler-Integration failed in Symfony 3.4/4.0

### ISSUE THREAD

**Issue by LinkingYou** [ldaptools/ldaptools-bundle#38]
In current symfony 3.4 with installed ldaptools-bundle, the web debug toolbar raises an error:

`Unable to find template "WebProfilerBundle:Profiler:layout.html.twig" (looked into: /home/user/PhpstormProjects/project/templates, /home/user/PhpstormProjects/project/templates, /home/user/PhpstormProjects/project/vendor/symfony/twig-bridge/Resources/views/Form) in @LdapTools/Collector/ldaptools.html.twig at line 1.`

If i change the first line in ldaptools-bundle/Resources/views/Collector/ldaptools.html.twig from:

`{% extends 'WebProfilerBundle:Profiler:layout.html.twig' %}`

to

`{% extends '@WebProfiler/Profiler/layout.html.twig' %}`

it works for me again.

**Comment by ChadSikorra** [comment]
Thanks for reporting this. I plan on fixing this and another open issue this weekend. Then I'll tag a new version.

**Comment by ChadSikorra** [comment]
This has been fixed and I tagged a new version.

**Comment by LinkingYou** [comment]
Thank you. Works perfect.
