### ISSUE TITLE
Prevent bundle to lookup groups/roles

### ISSUE THREAD

**Issue by althaus** [ldaptools/ldaptools-bundle#43]
Hey,

my customer reported some issues with his AD connection and after digging into the code, I've found out, that the bundle automatically is trying to load groups in the `LdapRoleMapper` on `loadUserByUsername()` ....even without any role mapping configured at all (edit: Which is the default value)!

Using a deep AD structure resulted in failed (timeout?) queries as the check is recursively by default, too.

The bundle shouldn't run the query if `$roles` is empty.

Cheers
Matthias

**Comment by ChadSikorra** [comment]
Thanks for helping resolve this. I've tagged a new minor version. Regarding the recursive check, that option can be toggled via configuration options for the bundle. The fact that it times out when querying recursively with (some of?) their user's really points toward poor group design / nesting unfortunately.
