### ISSUE TITLE
Unable to start TLS: Can't contact LDAP server

### ISSUE THREAD

**Issue by rarias8404** [ldaptools/ldaptools-bundle#55]
I am developing an API for AD. Everything works fine, except when I need to create a user and assign a password, because I need to make an ssl or tls connection. When I enable the ssl or tls options in ldap_tools.yml, I get the following error when connecting to the API: "Unable to start TLS: Can't contact LDAP server". Please, could someone help me with this error. I can telnet to ports 389 and 636, but from the API with TLS enabled I can't connect.
This is what I have in the configuration file:

ldap_tools:
    domains:       
        mydomain.local:             
            domain_name: mydomain.local            
            username: admin           
            password: mypassword            
            base_dn: "DC=mydomain,DC=local"            
            servers: ["AD"]
            #use_ssl: true
            #port: 636  
            #use_tls: true                        
    security:       
        refresh_user_roles: true
        roles:           
            ROLE_ADMIN: ['Admins']
            ROLE_USER: ['Users']
        guard:
            username_parameter: username
            password_parameter: password

**Comment by ChadSikorra** [comment]
Is this Windows or Linux? You need to add the LDAP CA cert to your OSs trusted certs (this works on Linux). Or there are more detailed instructions for doing the openldap conf config needed by PHP the config doc of this library (it has hard coded paths on windows). There's also a method on the LdapUtilities class for grabbing your LDAP cert.

**Comment by rarias8404** [comment]
Thanks for the reply. Yesterday I solved the problem, installing the AD CA
and creating the ldap.conf configuration file for windows. I had already
used the ldap.conf file within the symfony application, but it didn't work.
I had to create it in C:\openldap\sysconf and all good.

**Comment by ChadSikorra** [comment]
Glad to hear you got it working!
